### ISSUE TITLE
catkin build smb error reported

### ISSUE THREAD

**Issue by breadli428** [ETHZ-RobotX/SuperMegaBot#10]
![Screenshot from 2021-07-03 22-03-46](https://user-images.githubusercontent.com/57526478/124365796-93c84b80-dc4a-11eb-8eb3-f43b9aedc64d.png)

Hi,

When I did catkin build smb as written in installing hardware related software, I got the following error.

![Screenshot from 2021-07-03 22-05-35](https://user-images.githubusercontent.com/57526478/124365823-d722ba00-dc4a-11eb-8d70-28224295eb3a.png)

It did not affect me finishing other installations in the preparation smoothly, but I wonder if this is normal.

Thanks in advance.

Best,
Chenhao

**Comment by daBaret** [comment]
Hi Chenhao,
you actually need to build the package **smb** only on the robot. But if you want to do it also on your computer you have to import the repositories es stated in the guide.
```vcs import --recursive --input https://raw.githubusercontent.com/ETHZ-RobotX/SuperMegaBot/master/smb_hw.repos .``` 

Best,
Davide

**Comment by mantelt** [comment]
> Hi Chenhao,
> you actually need to build the package **smb** only on the robot. But if you want to do it also on your computer you have to import the repositories es stated in the guide.
> `vcs import --recursive --input https://raw.githubusercontent.com/ETHZ-RobotX/SuperMegaBot/master/smb_hw.repos .`
> 
> Best,
> Davide

In addition to that, you would also need to install the libspinnaker to successfully build all hardware related packages. But as @daBaret already pointed out, there is no need to build hardware related packages on your private computer. Those are only relevant on the robot itself.

**Comment by breadli428** [comment]
Hi Thomas and Davide,

Thanks for the reply. I thought we needed control the robot through our PC and that we had to install hardware related packages to realize this. Thanks for pointing it out.

Best,
Chenhao
