### ISSUE TITLE
rosdep error reported

### ISSUE THREAD

**Issue by breadli428** [ETHZ-RobotX/SuperMegaBot#11]
![Screenshot from 2021-07-03 23-17-14](https://user-images.githubusercontent.com/57526478/124367130-e4dd3d00-dc54-11eb-903c-78003de9a6da.png)

Hi,

As shown, there are some errors reported when executing rosdep... I tried to look into the source lists written in 20-default.list, indeed the reported variables are not defined there.

Fortunately this did not cause any problem during the preparation. I am not sure if this is normal therefore I am reporting it here. It would be super appreciated if you can inform how to deal with it.

Thanks as always.

Best,
Chenhao

**Comment by mantelt** [comment]
Hi Chenhao,

this question was already raised before: https://github.com/ETHZ-RobotX/SuperMegaBot/issues/5

In the end, the goal is to successfully build 

- `smb_gazebo` (for the simulation environment)
- `smb_path_planner` (for the path planner)
- `loam`, `ethzasl_msf`, `smb_msf` (for the state estimation tutorial)
- `cartographer_ros`, `cartographer_rviz` and `smb_slam` (for the mapping tutorial)
- `artefact_mapping` (for the artefact detection and mapping tutorial)

If you achieve that, you don't need to bother about the missing dependencies of other packages you don't actually need for summer school. 

I hope this clarifies things. 
Best,
Thomas

**Comment by breadli428** [comment]
Hi Thomas,

Thanks for the quick reply. This error reported by `rosdep` was exactly what caused the failure of building `smb_slam` during my first attempt (solved later by updating the repo), so it made me concerned on to what extend it affects.

But thanks for pointing out all we need eventually which helps a lot in understanding the whole structure. 

Best,
Chenhao
