### ISSUE TITLE
Absence of 2d Navigation Goal in the simulation

### ISSUE THREAD

**Issue by smartblond** [ETHZ-RobotX/SuperMegaBot#12]
Hi!

I am not sure, but it seems like I don't have opportunity to select "2d Navigation Goal" somewhere in toolbar during the simulation adjustment like it is written [here](https://ethz-robotx.github.io/SuperMegaBot/core-software/HowToRunSoftware.html) even though the simulation looks like it was described. Does it means that I have built something incorrect (the screen shot is attached)?
<img width="1172" alt="Снимок экрана 2021-07-04 в 10 46 56" src="https://user-images.githubusercontent.com/49717603/124379305-7d57d980-dcb6-11eb-8582-e3f0089ccbc7.png">

Thanks in advance.

Best, 
Daria

**Comment by daBaret** [comment]
Hi Daria,
thank you for your issue. 
You can find the "2D Navigation Goal" in rviz, not in gazebo.
![Screenshot from 2021-07-04 11-19-11](https://user-images.githubusercontent.com/29462014/124379871-d37a4c00-dcb9-11eb-8d54-0365a8cca2c2.png)

Let me know if this solved your issue.

Best,
Davide

**Comment by smartblond** [comment]
Thanks, David!

During the Rviz launching I got these errors, could you please advice me how I can try to address them?
<img width="741" alt="Снимок экрана 2021-07-04 в 11 41 21" src="https://user-images.githubusercontent.com/49717603/124380438-e17d9c00-dcbc-11eb-9d83-9daa71961244.png">

Best regards, Daria

**Comment by daBaret** [comment]
Hi Daria,
This is strange, it seems that you are missing some drivers.
Try **sudo apt-get install -y mesa-utils libgl1-mesa-glx**.
Let me know

**Comment by smartblond** [comment]
Unfortunately still the same.
I use Parallels as a VM, probably it is the cause of the problem.

**Comment by Hustwireless** [comment]
Hi Daria,
Which version of Ubuntu are you using?
This [page](https://askubuntu.com/questions/834254/steam-libgl-error-no-matching-fbconfigs-or-visuals-found-libgl-error-failed-t) might be helpful.

**Comment by smartblond** [comment]
I use Ubuntu 20.04 with the Parallels. I'll check the link, thanks.

**Comment by itaouil** [comment]
The issue was resolved by disabling 3D hardware acceleration (from VM settings) in case anyone else faces the same issue.
