### ISSUE TITLE
[navigate2d_ompl.launch] is neither a launch file in package...

### ISSUE THREAD

**Issue by RomeoV** [ETHZ-RobotX/SuperMegaBot#13]
Hi, I've been going through the installation steps, and everything seemed to be fine.
Unfortunately though, I was trying to run the simulation + navigation as detailed [here](https://ethz-robotx.github.io/SuperMegaBot/core-software/HowToRunSoftware.html#autonomous-navigation-in-simulation).
When running
```
roslaunch smb_navigation navigate2d_ompl.launch sim:=true global_frame:=tracking_camera_odom
```
I am getting the error 
```
RLException: [navigate2d_ompl.launch] is neither a launch file in package [smb_navigation] nor is [smb_navigation] a launch file name
```
But the file seems to exist:
```
cd <workspace>/src
ls smb_path_planner/smb_navigation/launch/navigate2d_ompl.launch
# file exists.
```

**Comment by mantelt** [comment]
Did you build the (meta-)package `smb_path_planner` ?

**Comment by grzemal** [comment]
Hi @RomeoV,
Did you sourced your workspace after building it?

**Comment by RomeoV** [comment]
Thanks @mantelt , that seems to have solved it!
