### ISSUE TITLE
Install dependencies

### ISSUE THREAD

**Issue by grizzi** [ETHZ-RobotX/SuperMegaBot#20]
This is not really an issue as all the missing deps can be installed separately after the installation procedure. 
- the simulation was missing the following unmet dependencies:
  - `ros-noetic-twist-mux` 
- the `smb_path_planner` required the following unmet deps:
  - `ros-noetic-base-local-planner`
  - `ros-noetic-navfn`
  - `ros-noetic-pointcloud-to-laserscan`
  - `ros-noetic-move-base`

Running the smb_path_planner would fail as no planner is built. So probably the `teb_local_planner` should be put as dep of the planner. When building the teb planner the following deps are unmet:
  - `ros-noetic-costmap-converter`
  - `ros-noetic-costmap-core`
  - `ros-noetic-mbf-msgs`
  - `ros-noetic-mbf-costmap-core`
  - `ros-noetic-libg2o`
 
Overall this deps can be easily installed manually and could be tedious for a student. The issue is with the scope of informing developers and help improve install instructions. Maybe the ros deps can be put in a `install_dependencies.bash` script instead of using rosdep which seems to fail at installing all dependencies.

**Comment by mantelt** [comment]
Thanks @grizzi , I somehow missed that issue! 
I think using rosdep should still work if the dependencies are carefully put into the package.xml. We will look into that.
