### ISSUE TITLE
Missing instruction for conda users

### ISSUE THREAD

**Issue by davidoort** [ETHZ-RobotX/SuperMegaBot#21]
If someone is using a fresh conda python environment, they'll have to install empy.
I had to run `conda install -c conda-forge empy` 
Otherwise, building smb_gazebo as mentioned in the installation instructions throws an error.

**Comment by davidoort** [comment]
As a follow-up when trying to run `roslaunch smb_gazebo sim.launch launch_gazebo_gui:=true` inside a conda env, I am missing the following dependencies: `rospkg defusedxml`
This can either be mentioned as part of the main instructions (though maybe conda is not recommended) or in the troubleshooting section.

**Comment by mantelt** [comment]
I have never used conda myself and thus never considered setting up the SMB environment using conda. But based on what I know about conda, and given the fact that you now are setting everything up in a conda environment, it might very well be worth having this extra information readily available for the participants/SMB users in the documentation.

**Comment by mantelt** [comment]
Solved with  ETHZ-RobotX/smb_dev#38
