### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by xkhainguyen** [ETHZ-RobotX/SuperMegaBot#32]
Hi,

I am running Ubuntu 20.04, ROS Noetic. I found these issues

1.
`rosdep install --from-paths . --ignore-src --os=ubuntu:focal -r -y`
should be:
`rosdep install --from-paths . --ignore-src -r -y` 
otherwise, it will be skipping some necessary packages like `twist_tmux`, `joy` and `teleop_twist_joy`

2.

> NODES
>   /
>     gazebo (gazebo_ros/gzserver)
>     gazebo_gui (gazebo_ros/gzclient)
>     rviz (rviz/rviz)
>     spawn_urdf (gazebo_ros/spawn_model)
>   /control/
>     controller_spawner (controller_manager/spawner)
>     smb_robot_state_publisher (robot_state_publisher/robot_state_publisher)
>     twist_mux (twist_mux/twist_mux)
>   /control/joy_teleop/
>     joy_e_stop_node (smb_control/joy_e_stop_node.py)
>     joy_node (joy/joy_node)
>     teleop_twist_joy (teleop_twist_joy/teleop_node)
>   /control/keyboard_teleop/
>     keyboard_teleop (teleop_twist_keyboard/teleop_twist_keyboard.py)
> 
> auto-starting new master
> process[master]: started with pid [2023186]
> ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to 515c4494-1777-11ee-97fd-5da10a309e71
> process[rosout-1]: started with pid [2023196]
> started core service [/rosout]
> process[control/controller_spawner-2]: started with pid [2023203]
> process[control/smb_robot_state_publisher-3]: started with pid [2023204]
> process[control/twist_mux-4]: started with pid [2023206]
> process[control/joy_teleop/joy_node-5]: started with pid [2023207]
> process[control/joy_teleop/teleop_twist_joy-6]: started with pid [2023212]
> process[control/joy_teleop/joy_e_stop_node-7]: started with pid [2023219]
> process[control/keyboard_teleop/keyboard_teleop-8]: started with pid [2023228]
> process[gazebo-9]: started with pid [2023229]
> process[gazebo_gui-10]: started with pid [2023232]
> process[spawn_urdf-11]: started with pid [2023237]
> process[rviz-12]: started with pid [2023241]
> [ WARN] [1688151174.345023677]: Couldn't set gain on joystick force feedback: Bad file descriptor
> [ INFO] [1688151174.656718898]: rviz version 1.14.20
> [ INFO] [1688151174.656772841]: compiled against Qt version 5.12.8
> [ INFO] [1688151174.656798022]: compiled against OGRE version 1.9.0 (Ghadamon)
> [ INFO] [1688151174.687455799]: Forcing OpenGl version 0.
> [INFO] [1688151175.009954, 0.000000]: Waiting for /clock to be available...
> Gazebo multi-robot simulator, version 11.11.0
> Copyright (C) 2012 Open Source Robotics Foundation.
> Released under the Apache 2 License.
> http://gazebosim.org
> 
> [Wrn] [GuiIface.cc:200] g/gui-plugin is really loading a SystemPlugin. To load a GUI plugin please use --gui-client-plugin 
> [INFO] [1688151175.359880, 0.000000]: Loading model XML from ros parameter smb_description
> [INFO] [1688151175.366425, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
> [ INFO] [1688151175.381724153]: Stereo is NOT SUPPORTED
> [ INFO] [1688151175.382002021]: OpenGL device: NVIDIA GeForce GTX 1050/PCIe/SSE2
> [ INFO] [1688151175.382090681]: OpenGl version: 4.6 (GLSL 4.6).
> Gazebo multi-robot simulator, version 11.11.0
> Copyright (C) 2012 Open Source Robotics Foundation.
> Released under the Apache 2 License.
> http://gazebosim.org
> 
> [ INFO] [1688151175.569321226]: Finished loading Gazebo ROS API Plugin.
> [ INFO] [1688151175.570422850]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
> [Msg] Waiting for master.
> [Msg] Connected to gazebo master @ http://127.0.0.1:11345
> [Msg] Publicized address: 192.168.123.135
> [ INFO] [1688151175.595432192]: Finished loading Gazebo ROS API Plugin.
> [Msg] Waiting for master.
> [ INFO] [1688151175.601487190]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
> [Msg] Connected to gazebo master @ http://127.0.0.1:11345
> [Msg] Publicized address: 192.168.123.135
> [Msg] Loading world file [/home/khai/smb_ws/src/core/smb_gazebo/worlds/WaA.world]
> [ INFO] [1688151176.665773146, 806.565000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
> [ INFO] [1688151176.702020356, 806.594000000]: Physics dynamic reconfigure ready.
> [Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/khai/smb_ws/src/core/smb_gazebo/include"
> [Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/khai/smb_ws/src/core/smb_gazebo/launch"
> [Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/khai/smb_ws/src/core/smb_gazebo/src"
> [Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/khai/smb_ws/src/core/smb_gazebo/worlds"
> [INFO] [1688151176.874827, 806.765000]: Calling service /gazebo/spawn_urdf_model
> [INFO] [1688151176.884236, 806.774000]: /clock is published. Proceeding to load the controller(s).
> [INFO] [1688151176.885965, 806.776000]: Controller Spawner: Waiting for service controller_manager/load_controller
> [Wrn] [ColladaLoader.cc:1928] Triangle input semantic: 'COLOR' is currently not supported
> [ INFO] [1688151179.722825947, 806.887000000]: Robosense laser plugin missing <min_intensity>, defaults to no clipping
> [ INFO] [1688151179.723958444, 806.887000000]: Robosense laser plugin ready, 16 lasers
> [INFO] [1688151179.730304, 806.887000]: Spawn status: SpawnModel: Successfully spawned entity
> [ INFO] [1688151180.001864623, 806.887000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
> [ INFO] [1688151180.004485400, 806.887000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
> [ INFO] [1688151180.111014319, 806.887000000]: Loading gazebo_ros_control plugin
> [ INFO] [1688151180.111136555, 806.887000000]: Starting gazebo_ros_control plugin in namespace: /control
> [ INFO] [1688151180.111692107, 806.887000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [/smb_description] on the ROS param server.
> [Wrn] [ColladaLoader.cc:1928] Triangle input semantic: 'COLOR' is currently not supported
> [ WARN] [1688151180.232797304, 806.887000000]: Joint LF_WHEEL_JOINT of transmission LF_WHEEL_TRANS specifies multiple hardware interfaces. Currently the default robot hardware simulation interface only supports one. Using the first entry
> [ WARN] [1688151180.251972224, 806.887000000]: Joint RF_WHEEL_JOINT of transmission RF_WHEEL_TRANS specifies multiple hardware interfaces. Currently the default robot hardware simulation interface only supports one. Using the first entry
> [ WARN] [1688151180.269029987, 806.887000000]: Joint LH_WHEEL_JOINT of transmission LH_WHEEL_TRANS specifies multiple hardware interfaces. Currently the default robot hardware simulation interface only supports one. Using the first entry
> [ WARN] [1688151180.286701261, 806.887000000]: Joint RH_WHEEL_JOINT of transmission RH_WHEEL_TRANS specifies multiple hardware interfaces. Currently the default robot hardware simulation interface only supports one. Using the first entry
> [ INFO] [1688151180.306359634, 806.887000000]: Loaded gazebo_ros_control.
> [ INFO] [1688151180.320237212, 806.887000000]: imu plugin missing <xyzOffset>, defaults to 0s
> [ INFO] [1688151180.320527925, 806.887000000]: imu plugin missing <rpyOffset>, defaults to 0s
> [spawn_urdf-11] process has finished cleanly
> log file: /home/khai/.ros/log/515c4494-1777-11ee-97fd-5da10a309e71/spawn_urdf-11*.log
> [INFO] [1688151180.510250, 807.022000]: Controller Spawner: Waiting for service controller_manager/switch_controller
> [INFO] [1688151180.513616, 807.023000]: Controller Spawner: Waiting for service controller_manager/unload_controller
> [INFO] [1688151180.517038, 807.029000]: Loading controller: smb_diff_drive
> [ INFO] [1688151180.530735575, 807.044000000]: Controller state will be published at 50Hz.
> [ INFO] [1688151180.531813881, 807.045000000]: Wheel separation will be multiplied by 1.
> [ INFO] [1688151180.532429081, 807.045000000]: Left wheel radius will be multiplied by 1.
> [ INFO] [1688151180.532532337, 807.046000000]: Right wheel radius will be multiplied by 1.
> [ INFO] [1688151180.533147830, 807.046000000]: Velocity rolling window size of 2.
> [ INFO] [1688151180.533826199, 807.047000000]: Velocity commands will be considered old if they are older than 0.25s.
> [ INFO] [1688151180.534142447, 807.047000000]: Allow mutiple cmd_vel publishers is enabled
> [ INFO] [1688151180.534821734, 807.048000000]: Base frame_id set to base_link
> [ INFO] [1688151180.535102318, 807.048000000]: Odometry frame_id set to odom
> [ INFO] [1688151180.535745808, 807.048000000]: Publishing to tf is disabled
> [ INFO] [1688151180.546937271, 807.057000000]: left wheel to origin: 0.2159,0.285, -0.0185
> [ INFO] [1688151180.546991696, 807.057000000]: right wheel to origin: 0.2159,-0.285, -0.0185
> [ INFO] [1688151180.547127897, 807.057000000]: Odometry params : wheel separation 0.57, left wheel radius 0.19, right wheel radius 0.19
> [ INFO] [1688151180.549490885, 807.058000000]: Adding left wheel with joint name: LF_WHEEL_JOINT and right wheel with joint name: RF_WHEEL_JOINT
> [ INFO] [1688151180.549673856, 807.058000000]: Adding left wheel with joint name: LH_WHEEL_JOINT and right wheel with joint name: RH_WHEEL_JOINT
> [ INFO] [1688151180.559063176, 807.067000000]: Dynamic Reconfigure:
> DynamicParams:
> 	Odometry parameters:
> 		left wheel radius multiplier: 1
> 		right wheel radius multiplier: 1
> 		wheel separation multiplier: 1
> 	Publication parameters:
> 		Publish executed velocity command: disabled
> 		Publication rate: 50
> 		Publish frame odom on tf: disabled
> [INFO] [1688151180.562846, 807.071000]: Loading controller: joint_state_controller
> [INFO] [1688151180.572764, 807.082000]: Controller Spawner: Loaded controllers: smb_diff_drive, joint_state_controller
>  [INFO] [1688151180.579086, 807.087000]: Started controllers: smb_diff_drive, joint_state_controller
> 

I cannot control it with `keyboard_teleop`

3. Trying to run Autonomous Navigation in Simulation

But rviz cannot load the costmap

> [ WARN] [1688151405.841563169, 1634.490000000]: Timed out waiting for transform from base_link to tracking_camera_odom to become available before running costmap, tf error: canTransform: target_frame tracking_camera_odom does not exist.. canTransform returned after 1634.49 timeout was 0.1.

Thanks

**Comment by MohamedNagyMostafa** [comment]
Hey @xkhainguyen , I have just open an issue ticker regarding the 3rd point you mentioned about 'tracking_camera_odom'. In fact, the 'tracking_camera_odom' coordinate is not shown at all in RViz.

**Comment by xkhainguyen** [comment]
Thanks for your response!
How about:
2) when Iaunched, there is no sign of keyboard_teleop running
3) there is no map in RViz and the warning is from the OMPL launch

**Comment by daBaret** [comment]
Hi,
thank you for reaching out.
1. happy it worked. Is actually strange but we always use this command for fresh installs. Thanks for finding the solution
2. Do keep the terminal selected while giving the inputs to keyboard_teleop? This only works if you select the terminal
3. Please look at  #33 

Let me know if everything works.
Have a nice day,
Davide

**Comment by xkhainguyen** [comment]
It seems that (3) can solve (2) as well. Thanks.
I hope you can update it to the tutorial.
