### ISSUE TITLE
tracking_camera_odom global frame not exist!

### ISSUE THREAD

**Issue by MohamedNagyMostafa** [ETHZ-RobotX/SuperMegaBot#33]
Hello, 

I am following instructions provided in your website: https://ethz-robotx.github.io/SuperMegaBot/core-software/HowToRunSoftware.html under subtitle "Autonomous Navigation in Simulation". I already run both commends
(1) "roslaunch smb_gazebo sim.launch launch_gazebo_gui:=true world:=planner_tutorial"
(2) "roslaunch smb_navigation navigate2d_ompl.launch sim:=true global_frame:=tracking_camera_odom"

But the "tracking_camera_odom" doesn't show up as an option in the list of the fixed frame in RViz. Moreover, I get the following warning (As the coordinates are not there anyway):

[ WARN] [1688371594.204723331, 3311.995000000]: Timed out waiting for transform from base_link to tracking_camera_odom to become available before running costmap, tf error: canTransform: target_frame tracking_camera_odom does not exist.. canTransform returned after 3311.99 timeout was 0.1.

There is no other warning or error message displayed in the 2nd commend terminal. However, the gazebo terminal (1st commend) shows some errors. (I believe they are not relevant to the problem)

![Screenshot from 2023-07-03 12-16-51](https://github.com/ETHZ-RobotX/SuperMegaBot/assets/20774864/0c7efd9b-d522-43b2-a1e8-24a061d9acd6)

Edit, This is the tf graph, the coordinate is not shown!

![Screenshot from 2023-07-03 12-34-05](https://github.com/ETHZ-RobotX/SuperMegaBot/assets/20774864/40fa559a-2d15-4451-a930-ca0ce9e51616)

**Comment by daBaret** [comment]
Hi Mohamed,
thanks for reaching out!
The tracking camera is disabled by default in the simulation. To launch it please run `roslaunch smb_gazebo sim.launch tracking_camera:=true`.

Let me know if it works.
Have a nice day,
Davide

**Comment by MohamedNagyMostafa** [comment]
Perfect! It is shown now. Thank you.

**Comment by MohamedNagyMostafa** [comment]
Hello!

Even though the "tracking_camera_odom" frame is available, but it seems something wrong. First of all, the robot model and the map doesn't receive any topics. I did check "add by topic" and there is no map published.

![Screenshot from 2023-07-03 13-36-03](https://github.com/ETHZ-RobotX/SuperMegaBot/assets/20774864/3d80dc71-a8bc-4a7e-8770-575392a325f7)



In addition, the commend "roslaunch smb_navigation navigate2d_ompl.launch sim:=true global_frame:=tracking_camera_odom" 's terminal shows the following error:


**_[ WARN] [1688377015.361505178, 2042.339000000]: Timed out waiting for transform from base_link to tracking_camera_odom to become available before running costmap, tf error: Could not find a connection between 'tracking_camera_odom' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.. canTransform returned after 0.1 timeout was 0.1._**

This is the tf tree after activating the tracking cam.
![Screenshot from 2023-07-03 13-37-58](https://github.com/ETHZ-RobotX/SuperMegaBot/assets/20774864/80d21122-94f4-41d7-bc67-c11e7e60d5aa)



I think all issues related to transforming to the "tracking_camera_odom". The transformation error displays everywhere; RobotModel,LiDAR Raw, ... Based on the tf tree, there is no connection between the two frames.

**Comment by daBaret** [comment]
What is the output of `rostopic list | grep camera`?
And `rosnode list`?

**Comment by MohamedNagyMostafa** [comment]
For `rostopic list | grep camera` :

_**/rgb_camera/camera_info
/rgb_camera/image_raw
/rgb_camera/image_raw/compressed
/rgb_camera/image_raw/compressed/parameter_descriptions
/rgb_camera/image_raw/compressed/parameter_updates
/rgb_camera/image_raw/compressedDepth
/rgb_camera/image_raw/compressedDepth/parameter_descriptions
/rgb_camera/image_raw/compressedDepth/parameter_updates
/rgb_camera/image_raw/theora
/rgb_camera/image_raw/theora/parameter_descriptions
/rgb_camera/image_raw/theora/parameter_updates
/rgb_camera/parameter_descriptions
/rgb_camera/parameter_updates
/tracking_camera/odom/sample**_

For `rosnode list` :

_**/control/controller_spawner
/control/joy_teleop/joy_e_stop_node
/control/joy_teleop/joy_node
/control/joy_teleop/teleop_twist_joy
/control/keyboard_teleop/keyboard_teleop
/control/smb_robot_state_publisher
/control/twist_mux
/gazebo
/gazebo_gui
/rosout
/rviz
/tracking_camera_odometry_conversion**_

**Comment by daBaret** [comment]
Do you get any output if you echo ` /tracking_camera/odom/sample`?

**Comment by MohamedNagyMostafa** [comment]
No, it doesn't publish anything.

**Comment by daBaret** [comment]
Did you get any error while launching the simulation? I think that the gazebo plugin for the tracking cam didn't launch

**Comment by MohamedNagyMostafa** [comment]
In fact, it shows some errors while launching ... below are screenshots of all "error + warning" msgs.

![Screenshot from 2023-07-03 14-39-21](https://github.com/ETHZ-RobotX/SuperMegaBot/assets/20774864/46e7db34-d963-4d15-92e6-9376b33644a8)

![Screenshot from 2023-07-03 14-41-07](https://github.com/ETHZ-RobotX/SuperMegaBot/assets/20774864/f05236f6-6b9a-4ecb-a618-268cb957610c)

This error below looks related:
![Screenshot from 2023-07-03 14-41-28](https://github.com/ETHZ-RobotX/SuperMegaBot/assets/20774864/51bd69f2-0ed8-4616-b5b9-eebf73bbb1d5)

And here, although it is 
![Screenshot from 2023-07-03 14-42-03](https://github.com/ETHZ-RobotX/SuperMegaBot/assets/20774864/35b8ce38-2e9e-4927-92ad-1a18af8959a9)
not an error, looks like odom is disabled (Don't know if it is related)


Then bunch of these errors, but I think not relevant.
![Screenshot from 2023-07-03 14-42-24](https://github.com/ETHZ-RobotX/SuperMegaBot/assets/20774864/7ac3c090-a2ea-4c9c-8767-42ce21703210)

**Comment by daBaret** [comment]
Did you run `rosdep install --from-paths . --ignore-src --os=ubuntu:focal -r -y` in you src folder? Could you run it again?
Could you also `catkin build smb_opc`?

**Comment by MohamedNagyMostafa** [comment]
Regarding "rosdep install --from-paths . --ignore-src --os=ubuntu:focal -r -y"

Output: **_#All required rosdeps installed successfully_**

Regarding: "catkin build smb_opc", it builds successfully.

but when I tried to build everything again `catkin build` to see if there is something wrong happens, I get the following output:

![Screenshot from 2023-07-03 15-01-13](https://github.com/ETHZ-RobotX/SuperMegaBot/assets/20774864/6cd1e4dc-4252-498e-9278-a74572d65119)

Followed by abandoning for the rest of packages:

 
![Screenshot from 2023-07-03 15-01-33](https://github.com/ETHZ-RobotX/SuperMegaBot/assets/20774864/b5d72c42-8646-4589-816a-76d8c8404ccb)

![Screenshot from 2023-07-03 15-01-49](https://github.com/ETHZ-RobotX/SuperMegaBot/assets/20774864/6b7f526b-60f3-4582-afba-a9bf7f4d333c)


I noticed that if I sourced the new `devel/setup.bash`, everything runs normally. So, I believe these errors happened during building the docker image so it wasn't obvious.

**Comment by daBaret** [comment]
Is not necessary to run `catkin build`, this will always fail. You don't have any hardware related packages on you pc.
Just run `catkin build smb_gazebo`

**Comment by MohamedNagyMostafa** [comment]
It is working now. I think building both `smb_gazebo`  and `smb_opc` solves the problem.

**Comment by daBaret** [comment]
Super, happy to hear that :)
