### ISSUE TITLE
SLAM Documentation

### ISSUE THREAD

**Issue by MohamedNagyMostafa** [ETHZ-RobotX/SuperMegaBot#34]
Hello!

I noticed that SLAM documentation in section "SLAM and Navigation" just mentions how to build the environment, without any details or examples about running the algorithm on the simulation environment. Is there any external documentation/s that can provide details about the "slam" package included in the SuperMegaBot sim?

Thank you,

**Comment by daBaret** [comment]
Hi,
is really nice to see how much you are already motivated!
We will release the documentation during the Robotic Summer School so that you have still something to do there ;)

Have a nice day,
Davide
