### ISSUE TITLE
smb simulation issues - no model showing in gazebo, no response in RViz to 2D nav command

### ISSUE THREAD

**Issue by abhayabhayabhay** [ETHZ-RobotX/SuperMegaBot#35]
Hello, 

I am running into some issues with the smb simulation. In gazebo, I see the WaA world appear and I see coordinates for the robot model but I do not see the robot model itself. Also when I follow the tutorial and set a goal for the planner using the 2D Navigation Goal tool, I do not see a response in RViz or Gazebo. 

I've included screenshots of the terminal, RViz, and Gazebo. Thank you for your help! 

Best,
Abhay 

![Screenshot from 2023-07-04 15-44-26](https://github.com/ETHZ-RobotX/SuperMegaBot/assets/69067026/710b7b3c-1fec-4d79-8fee-4376fd67d95a)

![Screenshot from 2023-07-04 15-47-21](https://github.com/ETHZ-RobotX/SuperMegaBot/assets/69067026/6d7fd2cd-d2c8-4f7b-a7e5-957b1099daa6)

![Screenshot from 2023-07-04 15-48-31](https://github.com/ETHZ-RobotX/SuperMegaBot/assets/69067026/eab2e2a0-6842-49c3-bb75-49da3e04ecf7)

**Comment by daBaret** [comment]
Hi Abhay,
Thank you for reaching out.
Please have a look to issue #33, this should solve your problem.
After you launched the tracking camera you should switch the global frame on the top left of Rviz to `tracking_camera_odom`.

Let me know if it work.

Have a nice day,
Davide

**Comment by abhayabhayabhay** [comment]
Hi Davide, 

Thank you for the quick response. Unfortunately, after following the steps in the issue #33, I am still running into the same error. I should mention that I ran into this error via native install rather than by docker. 

I did try running the docker container and followed the steps in issue #33; however I am running into errors with sim.launch. Below is a screenshot of the errors in terminal. 

Thanks for your help!

![image](https://github.com/ETHZ-RobotX/SuperMegaBot/assets/69067026/0d890574-ce5b-40ed-af97-b5e0272af438)

**Comment by daBaret** [comment]
Are you know trying on native install or in docker? Sorry i didn't get it

**Comment by erencanbulut** [comment]
Hello, I am one of RobotX Summer School participant. 

Sorry to involve the conversation. I had the same issue and solved it. Just wanted to share:

After terminate the current gazebo simulation, run the following command to check if there are any existing Gazebo processes running: `ps aux | grep gzserver` If you see any processes listed, then, you can use this command to terminate them: `killall -9 gzserver`

**Comment by abhayabhayabhay** [comment]
Hi,

Thank you so much for your response! Unfortunately, that did not work for
me. killall -9 gzserver does not seem to kill the gzserver process. When I
try using pkill instead, it the process appears to respawn with a new PID.
Do you have any advice for this? Thank you very much for your help!

Best,
Abhay

**Comment by erencanbulut** [comment]
Hi Abhay,

Unfortunately, I do not have time to check it now. Maybe we can look at it during the summer school. I also have some problems on my own simulation.

Best regards,
Can

**Comment by abhayabhayabhay** [comment]
Thank you Can, I look forward to meeting you!

Best,
Abhay
