### ISSUE TITLE
Working with Mac M1

### ISSUE THREAD

**Issue by thomasbirchler** [ETHZ-RobotX/SuperMegaBot#36]
Hello,

I'm not quite sure what the best option is to work with my MacBook Pro with M1 chip.

The first option you suggested (if one has Windows or a Linux system) is to use Docker. Then, you tell us to install VcXsrv, however, I think this is not available for Mac. So this first option does not work.
The second option is to install Ubuntu as an additional OS. This also does not work for the M1 ARM64 Chip.
The third option is to use UTM (or an other virtualisation tool, e.g. Parallels) to have Ubuntu in a virtual machine.

Am I right, that for me the only option is number three?

Kind regards,
Thomas

**Comment by daBaret** [comment]
Hi Thomas,
thanks for reaching out.

The third option would be the easiest one. We sadly don't support other methods.

You could also try to install Ubuntu ARM or search for some guides for how to run GUI application in docker on mac.
Sorry for the inconvenience.

Have a nice day,
Davide
