### ISSUE TITLE
teleop_twist_keyboard issue

### ISSUE THREAD

**Issue by erencanbulut** [ETHZ-RobotX/SuperMegaBot#38]
I am not able to move the robot because of the following issue:

![image](https://github.com/ETHZ-RobotX/SuperMegaBot/assets/54208292/47c7fe05-b11f-4ce1-b9e1-6eb0ac976751)

**Comment by daBaret** [comment]
Hi,
Did you get any error in the upper terminal?
You are probably missing twist_mux.
Please check with `sudo apt install ros-noetic-twist-mux`

**Comment by erencanbulut** [comment]
Hello, unfortunately it is not solved. I do not think the problem is about the twist_mux

Upper Terminal:

[ERROR] [1688669003.309345017]: Couldn't open joystick /dev/input/js0. Will retry every second.
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/roboteer/catkin_ws/src/smb_ws/src/core/smb_gazebo/include"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/roboteer/catkin_ws/src/smb_ws/src/core/smb_gazebo/launch"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/roboteer/catkin_ws/src/smb_ws/src/core/smb_gazebo/src"
[Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/roboteer/catkin_ws/src/smb_ws/src/core/smb_gazebo/worlds"

**Comment by shobhitsinghal1** [comment]
Hello Erencan
To me it looks like the twist teleop keyboard is not running in the right namespace. Please use the `keyboard_teleop:=true` parameter in the `smb.launch` launch file. That should already start the keyboard teleop in the same terminal.

**Comment by erencanbulut** [comment]
Hello,

I have already tried it before. It didn’t work.

**Comment by erencanbulut** [comment]
I forgot to put the correct cmdvel topic name. Here is the solution: 

`$ rostopic list | grep cmd ` # /control/opc/cmd_vel 
`$ rosrun teleop_twist_keyboard teleop_twist_keyboard.py /cmd_vel:=/control/opc/cmd_vel `
