### ISSUE TITLE
unable to load gazebo plugin

### ISSUE THREAD

**Issue by zcsun52** [ETHZ-RobotX/SuperMegaBot#39]
hi, when I try to run `roslaunch smb_gazebo sim.launch launch_gazebo_gui:=true world:=WaA`, gazebo is not starting and I got this error:
![Screenshot from 2023-07-06 23-43-28](https://github.com/ETHZ-RobotX/SuperMegaBot/assets/100108988/18ca2511-630d-42ca-8376-c17d9d1f5f01)

Please tell me if any additional info is needed, Thanks!

**Comment by daBaret** [comment]
Hi,
thank you for reaching out.
Could you try to `catkin build smb_gazebo` again?
Do you get any errors?

**Comment by zcsun52** [comment]
Hi,
I retried everything and its working fine now, thanks!
