### ISSUE TITLE
Error when catkin build smb_gazebo

### ISSUE THREAD

**Issue by Leon-LXA** [ETHZ-RobotX/SuperMegaBot#40]
I finished all steps before with all success, but when I try to build it shows the error below:

Errors     << robosense_gazebo_plugins:make /home/ruoyo/summerschool_ws/logs/robosense_gazebo_plugins/build.make.014.log                                                                                     
In file included from /usr/include/ignition/common3/ignition/common/Profiler.hh:18,
                 from /usr/include/gazebo-11/gazebo/common/Event.hh:32,
                 from /usr/include/gazebo-11/gazebo/physics/Joint.hh:27,
                 from /usr/include/gazebo-11/gazebo/physics/BallJoint.hh:25,
                 from /usr/include/gazebo-11/gazebo/physics/physics.hh:6,
                 from /home/ruoyo/summerschool_ws/src/hardware/robosense_simulator/robosense_gazebo_plugins/include/robosense_gazebo_plugins/GazeboRosRoboSenseLaser.h:49,
                 from /home/ruoyo/summerschool_ws/src/hardware/robosense_simulator/robosense_gazebo_plugins/src/GazeboRosRoboSenseLaser.cpp:35:
/usr/include/ignition/common3/gz/common/Profiler.hh:24:10: fatal error: gz/common/profiler/Export.hh: No such file or directory
   24 | #include <gz/common/profiler/Export.hh>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/gazebo_ros_robosense_laser.dir/build.make:76: CMakeFiles/gazebo_ros_robosense_laser.dir/src/GazeboRosRoboSenseLaser.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2079: CMakeFiles/gazebo_ros_robosense_laser.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /usr/include/ignition/common3/ignition/common/Profiler.hh:18,
                 from /usr/include/gazebo-11/gazebo/common/Event.hh:32,
                 from /usr/include/gazebo-11/gazebo/physics/Joint.hh:27,
                 from /usr/include/gazebo-11/gazebo/physics/BallJoint.hh:25,
                 from /usr/include/gazebo-11/gazebo/physics/physics.hh:6,
                 from /home/ruoyo/summerschool_ws/src/hardware/robosense_simulator/robosense_gazebo_plugins/include/robosense_gazebo_plugins/GazeboRosRoboSenseLaser.h:49,
                 from /home/ruoyo/summerschool_ws/src/hardware/robosense_simulator/robosense_gazebo_plugins/src/GazeboRosRoboSenseLaser.cpp:35:
/usr/include/ignition/common3/gz/common/Profiler.hh:24:10: fatal error: gz/common/profiler/Export.hh: No such file or directory
   24 | #include <gz/common/profiler/Export.hh>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/gazebo_ros_robosense_gpu_laser.dir/build.make:76: CMakeFiles/gazebo_ros_robosense_gpu_laser.dir/src/GazeboRosRoboSenseLaser.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2105: CMakeFiles/gazebo_ros_robosense_gpu_laser.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
cd /home/ruoyo/summerschool_ws/build/robosense_gazebo_plugins; catkin build --get-env robosense_gazebo_plugins | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

.............................................................................................................................................................................................................
Failed     << robosense_gazebo_plugins:make           [ Exited with code 2 ]                                                                                                                                 
Failed    <<< robosense_gazebo_plugins                [ 1.0 seconds ]                                                                                                                                        
Abandoned <<< smb_control                             [ Unrelated job failed ]                                                                                                                               
Abandoned <<< smb_description                         [ Unrelated job failed ]                                                                                                                               
Abandoned <<< smb_gazebo                              [ Unrelated job failed ]                                                                                                                               
Abandoned <<< smb_opc                                 [ Unrelated job failed ]                                                                                                                               
[build] Summary: 4 of 9 packages succeeded.                                                                                                                                                                  
[build]   Ignored:   106 packages were skipped or are skiplisted.                                                                                                                                            
[build]   Warnings:  None.                                                                                                                                                                                   
[build]   Abandoned: 4 packages were abandoned.                                                                                                                                                              
[build]   Failed:    1 packages failed.                                                                                                                                                                      
[build] Runtime: 1.1 seconds total.            

Then I tried to change  '#include <gz/common/profiler/Export.hh>' to '#include <gz/common/Export.hh>', it then shows error like this:

Errors     << robosense_gazebo_plugins:make /home/ruoyo/summerschool_ws/logs/robosense_gazebo_plugins/build.make.013.log                                                                                     
In file included from /usr/include/ignition/common3/ignition/common/Profiler.hh:18,
                 from /usr/include/gazebo-11/gazebo/common/Event.hh:32,
                 from /usr/include/gazebo-11/gazebo/physics/Joint.hh:27,
                 from /usr/include/gazebo-11/gazebo/physics/BallJoint.hh:25,
                 from /usr/include/gazebo-11/gazebo/physics/physics.hh:6,
                 from /home/ruoyo/summerschool_ws/src/hardware/robosense_simulator/robosense_gazebo_plugins/include/robosense_gazebo_plugins/GazeboRosRoboSenseLaser.h:49,
                 from /home/ruoyo/summerschool_ws/src/hardware/robosense_simulator/robosense_gazebo_plugins/src/GazeboRosRoboSenseLaser.cpp:35:
/usr/include/ignition/common3/gz/common/Profiler.hh:57:9: error: expected initializer before ‘:’ token
   57 |         : public virtual SingletonT<Profiler>
      |         ^
/usr/include/ignition/common3/gz/common/Profiler.hh:105:44: error: variable ‘ignition::common::IGNITION_COMMON_PROFILER_VISIBLE ignition::common::ScopedProfile’ has initializer but incomplete type
  105 |     class IGNITION_COMMON_PROFILER_VISIBLE ScopedProfile
      |                                            ^~~~~~~~~~~~~
/usr/include/ignition/common3/gz/common/Profiler.hh:111:7: error: expected primary-expression before ‘public’
  111 |       public: ScopedProfile(const char *_name, uint32_t *_hash)
      |       ^~~~~~
/usr/include/ignition/common3/gz/common/Profiler.hh:111:7: error: expected ‘}’ before ‘public’
/usr/include/ignition/common3/gz/common/Profiler.hh:106:5: note: to match this ‘{’
  106 |     {
      |     ^
/usr/include/ignition/common3/gz/common/Profiler.hh:111:7: error: expected ‘,’ or ‘;’ before ‘public’
  111 |       public: ScopedProfile(const char *_name, uint32_t *_hash)
      |       ^~~~~~
/usr/include/ignition/common3/gz/common/Profiler.hh:117:7: error: expected unqualified-id before ‘public’
  117 |       public: ~ScopedProfile()
      |       ^~~~~~
/usr/include/ignition/common3/gz/common/Profiler.hh:123:1: error: expected declaration before ‘}’ token
  123 | }
      | ^
In file included from /usr/include/ignition/common3/ignition/common/Profiler.hh:18,
                 from /usr/include/gazebo-11/gazebo/common/Event.hh:32,
                 from /usr/include/gazebo-11/gazebo/physics/Joint.hh:27,
                 from /usr/include/gazebo-11/gazebo/physics/BallJoint.hh:25,
                 from /usr/include/gazebo-11/gazebo/physics/physics.hh:6,
                 from /home/ruoyo/summerschool_ws/src/hardware/robosense_simulator/robosense_gazebo_plugins/include/robosense_gazebo_plugins/GazeboRosRoboSenseLaser.h:49,
                 from /home/ruoyo/summerschool_ws/src/hardware/robosense_simulator/robosense_gazebo_plugins/src/GazeboRosRoboSenseLaser.cpp:35:
/usr/include/ignition/common3/gz/common/Profiler.hh:57:9: error: expected initializer before ‘:’ token
   57 |         : public virtual SingletonT<Profiler>
      |         ^
/usr/include/ignition/common3/gz/common/Profiler.hh:105:44: error: variable ‘ignition::common::IGNITION_COMMON_PROFILER_VISIBLE ignition::common::ScopedProfile’ has initializer but incomplete type
  105 |     class IGNITION_COMMON_PROFILER_VISIBLE ScopedProfile
      |                                            ^~~~~~~~~~~~~
/usr/include/ignition/common3/gz/common/Profiler.hh:111:7: error: expected primary-expression before ‘public’
  111 |       public: ScopedProfile(const char *_name, uint32_t *_hash)
      |       ^~~~~~
/usr/include/ignition/common3/gz/common/Profiler.hh:111:7: error: expected ‘}’ before ‘public’
/usr/include/ignition/common3/gz/common/Profiler.hh:106:5: note: to match this ‘{’
  106 |     {
      |     ^
/usr/include/ignition/common3/gz/common/Profiler.hh:111:7: error: expected ‘,’ or ‘;’ before ‘public’
  111 |       public: ScopedProfile(const char *_name, uint32_t *_hash)
      |       ^~~~~~
/usr/include/ignition/common3/gz/common/Profiler.hh:117:7: error: expected unqualified-id before ‘public’
  117 |       public: ~ScopedProfile()
      |       ^~~~~~
/usr/include/ignition/common3/gz/common/Profiler.hh:123:1: error: expected declaration before ‘}’ token
  123 | }
      | ^
make[2]: *** [CMakeFiles/gazebo_ros_robosense_gpu_laser.dir/build.make:76: CMakeFiles/gazebo_ros_robosense_gpu_laser.dir/src/GazeboRosRoboSenseLaser.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2105: CMakeFiles/gazebo_ros_robosense_gpu_laser.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/gazebo_ros_robosense_laser.dir/build.make:76: CMakeFiles/gazebo_ros_robosense_laser.dir/src/GazeboRosRoboSenseLaser.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2079: CMakeFiles/gazebo_ros_robosense_laser.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
cd /home/ruoyo/summerschool_ws/build/robosense_gazebo_plugins; catkin build --get-env robosense_gazebo_plugins | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

.............................................................................................................................................................................................................
Failed     << robosense_gazebo_plugins:make           [ Exited with code 2 ]                                                                                                                                 
Failed    <<< robosense_gazebo_plugins                [ 7.8 seconds ]                                                                                                                                        
Abandoned <<< smb_control                             [ Unrelated job failed ]                                                                                                                               
Abandoned <<< smb_description                         [ Unrelated job failed ]                                                                                                                               
Abandoned <<< smb_gazebo                              [ Unrelated job failed ]                                                                                                                               
Abandoned <<< smb_opc                                 [ Unrelated job failed ]                                                                                                                               
[build] Summary: 4 of 9 packages succeeded.                                                                                                                                                                  
[build]   Ignored:   106 packages were skipped or are skiplisted.                                                                                                                                            
[build]   Warnings:  None.                                                                                                                                                                                   
[build]   Abandoned: 4 packages were abandoned.                                                                                                                                                              
[build]   Failed:    1 packages failed.                                                                                                                                                                      
[build] Runtime: 7.9 seconds total.

**Comment by shobhitsinghal1** [comment]
Hello Xuanang
Can you tell us:

- What worked till now?
- What commands did you run which failed?

**Comment by Leon-LXA** [comment]
> 

Hi，
I simply run 'catkin build smb_gazebo' and failed.

smb_control , smb_description and smb_navigation ... can be build.

**Comment by Leon-LXA** [comment]
> Hello Xuanang Can you tell us:
> 
> * What worked till now?
> * What commands did you run which failed?

Hi，
I simply run 'catkin build smb_gazebo' and failed.

smb_control , smb_description and smb_navigation ... can be build.
