### ISSUE TITLE
Unresolved rosdep keys

### ISSUE THREAD

**Issue by drehermarc** [ETHZ-RobotX/SuperMegaBot#5]
Hi there :)

After setting up ROS noetic (ros-noetic-desktop-full, [install guide](http://wiki.ros.org/noetic/Installation/Ubuntu)) in Ubuntu 20.04 LTS, I tried to set up the SMB Core software according to the [link](https://ethz-robotx.github.io/SuperMegaBot/core-software/installation_core.html) provided in the email. However while installing the system dependencies using rosdep I received an error message that certain rosdep keys could not be resolved:

user@HP:~/Desktop/smb_ws/src$ rosdep install --from-paths . --ignore-src --os=ubuntu:focal -r -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
spinnaker_camera_driver: Cannot locate rosdep definition for [opencv3]
ocs2_cmake_clang_tools: Cannot locate rosdep definition for [clang-tidy-7]
smb_mpc: Cannot locate rosdep definition for [ocs2_comm_interfaces]
smb_msf: Cannot locate rosdep definition for [msf_updates]
smb_slam: Cannot locate rosdep definition for [libpointmatcher]
ocs2_frank_wolfe: Cannot locate rosdep definition for [libglpk-dev]
smb_navigation_rviz: Cannot locate rosdep definition for [catkin_simple]
smb_navigation: Cannot locate rosdep definition for [traversability_estimation]
ocs2_doc: Cannot locate rosdep definition for [doxygen-latex]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully

I could install some of them (f.e. doxygen-latex), but the resolution of the corresponding rosdep key still fails:

user@HP:~/Desktop/smb_ws/src$ sudo apt install doxygen-latex
Reading package lists... Done
Building dependency tree       
Reading state information... Done
doxygen-latex is already the newest version (1.8.17-0ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Although the SMB Core Installation Guide says that "Note that, rosdep might not be able to install all dependencies.", I wanted to ask if such a big number of missing packages is "normal" and if anyone else has also encountered this issue and/or knows to resolve it.

The corresponding terminal output can be found in the following txt.
[terminal_output_missing_keys.txt](https://github.com/ETHZ-RobotX/SuperMegaBot/files/6734174/terminal_output_missing_keys.txt)

Thanks a lot for your effort.
Best,
Marc

**Comment by mantelt** [comment]
Hi Marc,
as far as I can tell, this should be fine. Most of them are custom packages not listed in the rosdep repository and thus triggering an error message. 

The main goal is that you can build the packages as documented, i.e. `smb_gazebo`. 

Best,
Thomas
