### ISSUE TITLE
sourcing ~/.bashrc failed

### ISSUE THREAD

**Issue by breadli428** [ETHZ-RobotX/SuperMegaBot#9]
![Screenshot from 2021-07-03 21-59-25](https://user-images.githubusercontent.com/57526478/124365704-fbca6200-dc49-11eb-8bd2-152f508fc689.png)

Hi,

I am having some trouble sourcing ~/.bashrc, even though it appeared in my folder. And I guess this caused the error in the first line in the screenshot.

It would be great if you know how to solve it. Thanks.

Best,
Chenhao

**Comment by daBaret** [comment]
Hi Chenhao,
Thank you for your issue
I think you have a mistake in your .bashrc. You have to edit the line that you are sourcing.
Edit you .bashrc file and where you wrote **source directory_to_ws/....**, change it with **source  ~/catkin_ws/devel/setup.bash**.

Let me know if it works :)
Best,
Davide

**Comment by breadli428** [comment]
Hi Davide,

Thanks for the instruction and it worked out perfectly. Seems I somehow copied the undefined command when echo the path ; )

Thanks and see you soon!

Best,
Chenhao
